### ISSUE TITLE
Can't start docular-server

### ISSUE THREAD

**Issue by SET001** [Vertafore/grunt-docular#13]
Can't start ducular server, it say that it can't find server configs, where to get them?

```
Failed to load server configs { [Error: Cannot find module '/home/set/www/gtdl/node_modules/grunt-docular/node_modules/docular/lib/nodeserver/configs/configs.js'] code: 'MODULE_NOT_FOUND' }
 { [Error: Command failed: connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0

events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: listen EADDRINUSE
    at errnoException (net.js:770:11)
    at Server._listen2 (net.js:910:14)
    at listen (net.js:937:10)
    at Server.listen (net.js:986:5)
    at Function.app.listen (/home/set/www/gtdl/node_modules/grunt-docular/node_modules/docular/node_modules/express/lib/application.js:533:24)
    at main (/home/set/www/gtdl/node_modules/grunt-docular/node_modules/docular/lib/nodeserver/server.js:131:9)
    at /home/set/www/gtdl/node_modules/grunt-docular/node_modules/docular/lib/nodeserver/server.js:168:5
    at _fulfilled (/home/set/www/gtdl/node_modules/grunt-docular/node_modules/docular/node_modules/q/q.js:797:54)
    at Promise.then.self.promiseDispatch.done (/home/set/www/gtdl/node_modules/grunt-docular/node_modules/docular/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/home/set/www/gtdl/node_modules/grunt-docular/node_modules/docular/node_modules/q/q.js:759:13)
] killed: false, code: 1, signal: null } connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0

events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: listen EADDRINUSE
    at errnoException (net.js:770:11)
    at Server._listen2 (net.js:910:14)
    at listen (net.js:937:10)
    at Server.listen (net.js:986:5)
    at Function.app.listen (/home/set/www/gtdl/node_modules/grunt-docular/node_modules/docular/node_modules/express/lib/application.js:533:24)
    at main (/home/set/www/gtdl/node_modules/grunt-docular/node_modules/docular/lib/nodeserver/server.js:131:9)
    at /home/set/www/gtdl/node_modules/grunt-docular/node_modules/docular/lib/nodeserver/server.js:168:5
    at _fulfilled (/home/set/www/gtdl/node_modules/grunt-docular/node_modules/docular/node_modules/q/q.js:797:54)
    at Promise.then.self.promiseDispatch.done (/home/set/www/gtdl/node_modules/grunt-docular/node_modules/docular/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/home/set/www/gtdl/node_modules/grunt-docular/node_modules/docular/node_modules/q/q.js:759:13)
```

and here is my Grunt.js:

```
module.exports = function(grunt) {

  // Project configuration
  grunt.initConfig({

    pkg: grunt.file.readJSON('package.json'),

    docular: {
      baseUrl: '/', //base tag used by Angular
      showAngularDocs: true, //parse and render Angular documentation
      showDocularDocs: true, //parse and render Docular documentation
      docAPIOrder : ['doc', 'angular'], //order to load ui resources
      groups: [] //groups of documentation to parse
    }

  });

  // Load the plugin that provides the "docular" tasks.
  grunt.loadNpmTasks('grunt-docular');

  // Default task(s).
  grunt.registerTask('default', ['docular']);

};
```

**Comment by Kadajett** [comment]
I am having the same issue

**Comment by eadlam** [comment]
I'm having this issue too.

**Comment by Kadajett** [comment]
I ended up just running a python server in its place, worked fine. But maybe check and kill other grunt tasks.

**Comment by joewoodhouse** [comment]
I'm getting this too, seems totally unusable at the moment?

**Comment by Kadajett** [comment]
I can take a look too, I'll see what I can find, but again, until this is good, you CAN run a python server with another port to actually test your stuff.

**Comment by joewoodhouse** [comment]
Pull request for potential fix (it sorts the above for me at least)
https://github.com/gitsome/docular/pull/98

**Comment by theluckin** [comment]
@Kadajett , any idea how to hook up with a nodejs sever?

**Comment by laurelnaiad** [comment]
It sure looks like a port problem.  See my pull request for info on two possibilities to run on a different port: https://github.com/gitsome/grunt-docular/pull/3 .  The short answer is:

```
grunt docular-server:8001
```

 HTH

**Comment by arthurhenning** [comment]
The file node_modules/grunt-docular/node_modules/docular/lib/nodeserver/configs/configs.js is missing from my project. Any ideas why?

**Comment by arthurhenning** [comment]
Never mind, I've managed to fix it using https://github.com/gitsome/docular/issues/99 .
